### PR TITLE
[1171] Fix overflow behavior when side panels are resized

### PR DESCRIPTION
**Pull request by pcdavid**
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1171

https://user-images.githubusercontent.com/10608/164465578-9d10e955-e55a-493c-8a65-b0ac249e2fb6.mp4

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Comment by sbegaudeau** [comment]
The proper fix should probably be `min-width: 0;` on the CSS class `view`.

**Comment by pcdavid** [comment]
> The proper fix should probably be `min-width: 0;` on the CSS class `view`.

I'll try that.

**Comment by sbegaudeau** [comment]
I've updated the PR to ask both you and @gcoutable to try it, if it works I'll squash the whole thing :)

**Comment by pcdavid** [comment]
OK, your commit arrived while I was writing my comment :) I'll test this new version.

**Comment by sbegaudeau** [comment]
Don't ask me how I came to this conclusion and why it seems to make sense 😄 

https://www.youtube.com/watch?v=K-mUbYvSFz0

**Comment by pcdavid** [comment]
With the `min-width` I get this (tested under Chrome and Firefox):

**Comment by sbegaudeau** [comment]
There was a missing overflow on the header

**Comment by pcdavid** [comment]
Better, but I did not expect a scroll-bar on the header. That's debatable but maybe `overflow: hidden` for this?

Also, I get a strange behavior for just a part of the SVG icon in the header:

https://user-images.githubusercontent.com/10608/166889896-bc5cf971-ed82-493f-b808-60e6b2ec0aa2.mp4

**Comment by gcoutable** [comment]
Maybe, that can be "fixed" by increasing the minimal panel size?

**Comment by sbegaudeau** [comment]
I see why we have that, the padding is not computed as part of the size of the flex box element

**Comment by pcdavid** [comment]
The version in https://github.com/eclipse-sirius/sirius-components/commit/2c752c21fe7936c24bd1647ddb818e260d9a11e5 works for me :+1:

**Comment by gcoutable** [comment]
https://github.com/eclipse-sirius/sirius-components/commit/2c752c21fe7936c24bd1647ddb818e260d9a11e5 works for me too

**Comment by sbegaudeau** [comment]
Thanks for the quick feedback, I'll squash that and merge it after the build.

77M0

**Review by sbegaudeau — APPROVED** [review]

**Pull request merged**
